# Generated by Django 5.0.4 on 2024-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
