# Generated by Django 5.0.4 on 2024-05-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_product_category_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('ML', 'Milk'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
