# Generated by Django 5.0.4 on 2024-05-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
