# Generated by Django 5.0.4 on 2024-05-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('GH', 'Ghee'), ('ML', 'Milk'), ('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('CZ', 'Cheese'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
