# Generated by Django 5.0.4 on 2024-05-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_product_category_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('LS', 'Lassi'), ('CZ', 'Cheese'), ('ML', 'Milk'), ('GH', 'Ghee'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
