# Generated by Django 5.0.4 on 2024-05-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_alter_product_category_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('ML', 'Milk'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('MS', 'Milkshake'), ('CR', 'Curd'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
