# Generated by Django 5.0.4 on 2024-05-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('MS', 'Milkshake'), ('ML', 'Milk'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
