# Generated by Django 5.0.4 on 2024-05-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('CZ', 'Cheese'), ('GH', 'Ghee')], max_length=2),
        ),
    ]
