# Generated by Django 5.0.4 on 2024-05-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('ML', 'Milk'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('CR', 'Curd'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
