# Generated by Django 5.0.4 on 2024-05-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('GH', 'Ghee'), ('CR', 'Curd'), ('MS', 'Milkshake'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
